// Auto-generated shim for @google/jules-sdk
// Re-run: bun scripts/gen-shim.ts @google/jules-sdk src/types/jules-sdk.ts
//
// Import everything jules-sdk-related from here.
// Never import directly from '@google/jules-sdk' in the app — one re-run keeps this current.


export {
  ACTIVITY_SCHEMA,
  AutomatedSessionFailedError,
  BashArtifact,
  ChangeSetArtifact,
  FILTER_OP_SCHEMA,
  InvalidStateError,
  JulesApiError,
  JulesAuthenticationError,
  JulesClientImpl,
  JulesError,
  JulesNetworkError,
  JulesRateLimitError,
  MemorySessionStorage,
  MemoryStorage,
  MissingApiKeyError,
  NodePlatform,
  PROJECTION_SCHEMA,
  SESSION_SCHEMA,
  SessionCursor,
  SourceNotFoundError,
  SyncInProgressError,
  TimeoutError,
  connect,
  formatValidationResult,
  generateMarkdownDocs,
  generateTypeDefinition,
  getAllSchemas,
  getSchema,
  jules,
  parseUnidiff,
  toSummary,
  validateQuery,
} from '@google/jules-sdk'

export type {
  Activity,
  ActivityAgentMessaged,
  ActivityPlanApproved,
  ActivityPlanGenerated,
  ActivityProgressUpdated,
  ActivitySessionCompleted,
  ActivitySessionFailed,
  ActivitySummary,
  ActivityUserMessaged,
  Artifact,
  AutomatedSession,
  ChangeSet,
  DomainSchema,
  FieldMeta,
  GitHubRepo,
  GitPatch,
  JulesClient,
  JulesDomain,
  JulesOptions,
  JulesQuery,
  LightweightActivity,
  LightweightArtifact,
  ListSessionsOptions,
  ListSessionsResponse,
  MediaArtifact,
  Outcome,
  ParsedChangeSet,
  ParsedFile,
  Plan,
  PlanStep,
  Platform,
  PullRequest,
  QueryExample,
  SerializedSnapshot,
  SessionClient,
  SessionConfig,
  SessionOutput,
  SessionResource,
  SessionState,
  SnapshotField,
  Source,
  SourceContext,
  SourceInput,
  SourceManager,
  StorageFactory,
  StrippedMediaArtifact,
  SyncDepth,
  ToJSONOptions,
  ValidationError,
  ValidationErrorCode,
  ValidationResult,
  ValidationWarning,
} from '@google/jules-sdk'
